-- MySQL Script generated by MySQL Workbench
-- Wed Jan  5 09:15:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pay` DEFAULT CHARACTER SET utf8 ;
USE `pay` ;

-- -----------------------------------------------------
-- Table `pay`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`employee` (
  `idemployee` BIGINT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `age` INT NULL,
  `start_date` DATE NULL,
  `adress` VARCHAR(45) NULL,
  `status_marital` TINYINT NULL,
  `enfant` INT NULL,
  PRIMARY KEY (`idemployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`team` (
  `idteam` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idemployee` BIGINT NOT NULL,
  PRIMARY KEY (`idteam`),
  INDEX `fk_team_employee1_idx` (`idemployee` ASC) VISIBLE,
  CONSTRAINT `fk_team_employee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `pay`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`client` (
  `idclient` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`project` (
  `idproject` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `budget` FLOAT NULL,
  `idteam` BIGINT NOT NULL,
  PRIMARY KEY (`idproject`),
  INDEX `fk_project_team1_idx` (`idteam` ASC) VISIBLE,
  CONSTRAINT `fk_project_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `pay`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`timeOff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`timeOff` (
  `idtimeOff` BIGINT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `raison` VARCHAR(45) NULL,
  `idemployee` BIGINT NOT NULL,
  PRIMARY KEY (`idtimeOff`),
  INDEX `fk_timeOff_employee1_idx` (`idemployee` ASC) VISIBLE,
  CONSTRAINT `fk_timeOff_employee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `pay`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`holidays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`holidays` (
  `idholidays` BIGINT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `idteam` BIGINT NOT NULL,
  `idemployee` BIGINT NOT NULL,
  PRIMARY KEY (`idholidays`),
  INDEX `fk_holidays_team1_idx` (`idteam` ASC) VISIBLE,
  INDEX `fk_holidays_employee1_idx` (`idemployee` ASC) VISIBLE,
  CONSTRAINT `fk_holidays_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `pay`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_holidays_employee1`
    FOREIGN KEY (`idemployee`)
    REFERENCES `pay`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`profile` (
  `idprofile` BIGINT NOT NULL AUTO_INCREMENT,
  `type_profile` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`emp_proj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`emp_proj` (
  `idemp_proj` BIGINT NOT NULL AUTO_INCREMENT,
  `idemployee` BIGINT NOT NULL,
  `idproject` BIGINT NOT NULL,
  PRIMARY KEY (`idemp_proj`),
  INDEX `fk_employee_idx` (`idemployee` ASC) VISIBLE,
  INDEX `fk_project_idx` (`idproject` ASC) VISIBLE,
  CONSTRAINT `fk_employee`
    FOREIGN KEY (`idemployee`)
    REFERENCES `pay`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project`
    FOREIGN KEY (`idproject`)
    REFERENCES `pay`.`project` (`idproject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`empl_prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`empl_prof` (
  `idempl_prof` BIGINT NOT NULL AUTO_INCREMENT,
  `idemployee` BIGINT NOT NULL,
  `idprofile` BIGINT NOT NULL,
  `idteam` BIGINT NOT NULL,
  PRIMARY KEY (`idempl_prof`),
  INDEX `fk_employee_idx` (`idemployee` ASC) VISIBLE,
  INDEX `fk_profile_idx` (`idprofile` ASC) VISIBLE,
  INDEX `fk_empl_prof_team1_idx` (`idteam` ASC) VISIBLE,
  CONSTRAINT `fk_employee`
    FOREIGN KEY (`idemployee`)
    REFERENCES `pay`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile`
    FOREIGN KEY (`idprofile`)
    REFERENCES `pay`.`profile` (`idprofile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empl_prof_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `pay`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pay`.`client_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay`.`client_project` (
  `idclient_project` BIGINT NOT NULL AUTO_INCREMENT,
  `idclient` BIGINT NOT NULL,
  `idproject` BIGINT NOT NULL,
  PRIMARY KEY (`idclient_project`),
  INDEX `fk_client_idx` (`idclient` ASC) VISIBLE,
  INDEX `fk_project_idx` (`idproject` ASC) VISIBLE,
  CONSTRAINT `fk_client`
    FOREIGN KEY (`idclient`)
    REFERENCES `pay`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project`
    FOREIGN KEY (`idproject`)
    REFERENCES `pay`.`project` (`idproject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
